# Generated by Django 4.0.3 on 2022-05-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_contacto_avisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_de_producto',
        ),
    ]
